version: '3.7'

services:
  frontend:
    build:
      context: ./apps/frontend/.
    ports:
      - "3003:3000"
    command: npm run serve
    depends_on:
      - backend

  backend:
    build: ./apps/backend/.
    command: node app.js
    ports:
      - "3002:3002"

